/*
 * API
 * TheMovieDB API
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MoviedetailsobjectProductionCountries
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-27T19:30:00.618+02:00")
public class MoviedetailsobjectProductionCountries {
  @SerializedName("iso_3166_1")
  private String iso31661 = null;

  @SerializedName("name")
  private String name = null;

  public MoviedetailsobjectProductionCountries iso31661(String iso31661) {
    this.iso31661 = iso31661;
    return this;
  }

   /**
   * Get iso31661
   * @return iso31661
  **/
  @ApiModelProperty(value = "")
  public String getIso31661() {
    return iso31661;
  }

  public void setIso31661(String iso31661) {
    this.iso31661 = iso31661;
  }

  public MoviedetailsobjectProductionCountries name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoviedetailsobjectProductionCountries moviedetailsobjectProductionCountries = (MoviedetailsobjectProductionCountries) o;
    return Objects.equals(this.iso31661, moviedetailsobjectProductionCountries.iso31661) &&
        Objects.equals(this.name, moviedetailsobjectProductionCountries.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iso31661, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoviedetailsobjectProductionCountries {\n");
    
    sb.append("    iso31661: ").append(toIndentedString(iso31661)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

