/*
 * API
 * TheMovieDB API
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MoviedetailsobjectSpokenLanguages
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-27T19:30:00.618+02:00")
public class MoviedetailsobjectSpokenLanguages {
  @SerializedName("iso_639_1")
  private String iso6391 = null;

  @SerializedName("name")
  private String name = null;

  public MoviedetailsobjectSpokenLanguages iso6391(String iso6391) {
    this.iso6391 = iso6391;
    return this;
  }

   /**
   * Get iso6391
   * @return iso6391
  **/
  @ApiModelProperty(value = "")
  public String getIso6391() {
    return iso6391;
  }

  public void setIso6391(String iso6391) {
    this.iso6391 = iso6391;
  }

  public MoviedetailsobjectSpokenLanguages name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoviedetailsobjectSpokenLanguages moviedetailsobjectSpokenLanguages = (MoviedetailsobjectSpokenLanguages) o;
    return Objects.equals(this.iso6391, moviedetailsobjectSpokenLanguages.iso6391) &&
        Objects.equals(this.name, moviedetailsobjectSpokenLanguages.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iso6391, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoviedetailsobjectSpokenLanguages {\n");
    
    sb.append("    iso6391: ").append(toIndentedString(iso6391)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

