/*
 * API
 * TheMovieDB API
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MovieDetailsObject
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-27T19:30:00.618+02:00")
public class MovieDetailsObject {
  @SerializedName("adult")
  private Boolean adult = null;

  public Boolean getAdult() {
    return adult;
  }

  public void setAdult(Boolean adult) {
    this.adult = adult;
  }

  public String getBackdropPath() {
    return backdropPath;
  }

  public void setBackdropPath(String backdropPath) {
    this.backdropPath = backdropPath;
  }

  public String getPosterPath() {
    return posterPath;
  }

  public void setPosterPath(String posterPath) {
    this.posterPath = posterPath;
  }

  public Boolean getVideo() {
    return video;
  }

  @SerializedName("backdrop_path")
  private String backdropPath = null;

  @SerializedName("budget")
  private Integer budget = null;

  @SerializedName("genres")
  private List<MoviedetailsobjectGenres> genres = null;

  @SerializedName("homepage")
  private String homepage = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("imdb_id")
  private String imdbId = null;

  @SerializedName("original_language")
  private String originalLanguage = null;

  @SerializedName("original_title")
  private String originalTitle = null;

  @SerializedName("overview")
  private String overview = null;

  @SerializedName("popularity")
  private BigDecimal popularity = null;

  @SerializedName("poster_path")
  private String posterPath = null;

  @SerializedName("production_companies")
  private List<MoviedetailsobjectProductionCompanies> productionCompanies = null;

  @SerializedName("production_countries")
  private List<MoviedetailsobjectProductionCountries> productionCountries = null;

  @SerializedName("release_date")
  private String releaseDate = null;

  @SerializedName("revenue")
  private Long revenue = null;

  @SerializedName("runtime")
  private Integer runtime = null;

  @SerializedName("spoken_languages")
  private List<MoviedetailsobjectSpokenLanguages> spokenLanguages = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("tagline")
  private String tagline = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("video")
  private Boolean video = null;

  @SerializedName("vote_average")
  private BigDecimal voteAverage = null;

  @SerializedName("vote_count")
  private Integer voteCount = null;

  public MovieDetailsObject adult(Boolean adult) {
    this.adult = adult;
    return this;
  }

   /**
   * Get budget
   * @return budget
  **/
  @ApiModelProperty(value = "")
  public Integer getBudget() {
    return budget;
  }

  public void setBudget(Integer budget) {
    this.budget = budget;
  }

  public MovieDetailsObject genres(List<MoviedetailsobjectGenres> genres) {
    this.genres = genres;
    return this;
  }

  public MovieDetailsObject addGenresItem(MoviedetailsobjectGenres genresItem) {
    if (this.genres == null) {
      this.genres = new ArrayList<MoviedetailsobjectGenres>();
    }
    this.genres.add(genresItem);
    return this;
  }

   /**
   * Get genres
   * @return genres
  **/
  @ApiModelProperty(value = "")
  public List<MoviedetailsobjectGenres> getGenres() {
    return genres;
  }

  public void setGenres(List<MoviedetailsobjectGenres> genres) {
    this.genres = genres;
  }

  public MovieDetailsObject homepage(String homepage) {
    this.homepage = homepage;
    return this;
  }

   /**
   * Get homepage
   * @return homepage
  **/
  @ApiModelProperty(value = "")
  public String getHomepage() {
    return homepage;
  }

  public void setHomepage(String homepage) {
    this.homepage = homepage;
  }

  public MovieDetailsObject id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MovieDetailsObject imdbId(String imdbId) {
    this.imdbId = imdbId;
    return this;
  }

   /**
   * Get imdbId
   * @return imdbId
  **/
  @ApiModelProperty(value = "")
  public String getImdbId() {
    return imdbId;
  }

  public void setImdbId(String imdbId) {
    this.imdbId = imdbId;
  }

  public MovieDetailsObject originalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
    return this;
  }

   /**
   * Get originalLanguage
   * @return originalLanguage
  **/
  @ApiModelProperty(value = "")
  public String getOriginalLanguage() {
    return originalLanguage;
  }

  public void setOriginalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
  }

  public MovieDetailsObject originalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
    return this;
  }

   /**
   * Get originalTitle
   * @return originalTitle
  **/
  @ApiModelProperty(value = "")
  public String getOriginalTitle() {
    return originalTitle;
  }

  public void setOriginalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
  }

  public MovieDetailsObject overview(String overview) {
    this.overview = overview;
    return this;
  }

   /**
   * Get overview
   * @return overview
  **/
  @ApiModelProperty(value = "")
  public String getOverview() {
    return overview;
  }

  public void setOverview(String overview) {
    this.overview = overview;
  }

  public MovieDetailsObject popularity(BigDecimal popularity) {
    this.popularity = popularity;
    return this;
  }

   /**
   * Get popularity
   * @return popularity
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPopularity() {
    return popularity;
  }

  public void setPopularity(BigDecimal popularity) {
    this.popularity = popularity;
  }


  public MovieDetailsObject productionCompanies(List<MoviedetailsobjectProductionCompanies> productionCompanies) {
    this.productionCompanies = productionCompanies;
    return this;
  }

  public MovieDetailsObject addProductionCompaniesItem(MoviedetailsobjectProductionCompanies productionCompaniesItem) {
    if (this.productionCompanies == null) {
      this.productionCompanies = new ArrayList<MoviedetailsobjectProductionCompanies>();
    }
    this.productionCompanies.add(productionCompaniesItem);
    return this;
  }

   /**
   * Get productionCompanies
   * @return productionCompanies
  **/
  @ApiModelProperty(value = "")
  public List<MoviedetailsobjectProductionCompanies> getProductionCompanies() {
    return productionCompanies;
  }

  public void setProductionCompanies(List<MoviedetailsobjectProductionCompanies> productionCompanies) {
    this.productionCompanies = productionCompanies;
  }

  public MovieDetailsObject productionCountries(List<MoviedetailsobjectProductionCountries> productionCountries) {
    this.productionCountries = productionCountries;
    return this;
  }

  public MovieDetailsObject addProductionCountriesItem(MoviedetailsobjectProductionCountries productionCountriesItem) {
    if (this.productionCountries == null) {
      this.productionCountries = new ArrayList<MoviedetailsobjectProductionCountries>();
    }
    this.productionCountries.add(productionCountriesItem);
    return this;
  }

   /**
   * Get productionCountries
   * @return productionCountries
  **/
  @ApiModelProperty(value = "")
  public List<MoviedetailsobjectProductionCountries> getProductionCountries() {
    return productionCountries;
  }

  public void setProductionCountries(List<MoviedetailsobjectProductionCountries> productionCountries) {
    this.productionCountries = productionCountries;
  }

  public MovieDetailsObject releaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @ApiModelProperty(value = "")
  public String getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
  }

  public MovieDetailsObject revenue(Long revenue) {
    this.revenue = revenue;
    return this;
  }

   /**
   * Get revenue
   * @return revenue
  **/
  @ApiModelProperty(value = "")
  public Long getRevenue() {
    return revenue;
  }

  public void setRevenue(Long revenue) {
    this.revenue = revenue;
  }

  public MovieDetailsObject runtime(Integer runtime) {
    this.runtime = runtime;
    return this;
  }

   /**
   * Get runtime
   * @return runtime
  **/
  @ApiModelProperty(value = "")
  public Integer getRuntime() {
    return runtime;
  }

  public void setRuntime(Integer runtime) {
    this.runtime = runtime;
  }

  public MovieDetailsObject spokenLanguages(List<MoviedetailsobjectSpokenLanguages> spokenLanguages) {
    this.spokenLanguages = spokenLanguages;
    return this;
  }

  public MovieDetailsObject addSpokenLanguagesItem(MoviedetailsobjectSpokenLanguages spokenLanguagesItem) {
    if (this.spokenLanguages == null) {
      this.spokenLanguages = new ArrayList<MoviedetailsobjectSpokenLanguages>();
    }
    this.spokenLanguages.add(spokenLanguagesItem);
    return this;
  }

   /**
   * Get spokenLanguages
   * @return spokenLanguages
  **/
  @ApiModelProperty(value = "")
  public List<MoviedetailsobjectSpokenLanguages> getSpokenLanguages() {
    return spokenLanguages;
  }

  public void setSpokenLanguages(List<MoviedetailsobjectSpokenLanguages> spokenLanguages) {
    this.spokenLanguages = spokenLanguages;
  }

  public MovieDetailsObject status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public MovieDetailsObject tagline(String tagline) {
    this.tagline = tagline;
    return this;
  }

   /**
   * Get tagline
   * @return tagline
  **/
  @ApiModelProperty(value = "")
  public String getTagline() {
    return tagline;
  }

  public void setTagline(String tagline) {
    this.tagline = tagline;
  }

  public MovieDetailsObject title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public MovieDetailsObject video(Boolean video) {
    this.video = video;
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  @ApiModelProperty(value = "")
  public Boolean isVideo() {
    return video;
  }

  public void setVideo(Boolean video) {
    this.video = video;
  }

  public MovieDetailsObject voteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
    return this;
  }

   /**
   * Get voteAverage
   * @return voteAverage
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getVoteAverage() {
    return voteAverage;
  }

  public void setVoteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
  }

  public MovieDetailsObject voteCount(Integer voteCount) {
    this.voteCount = voteCount;
    return this;
  }

   /**
   * Get voteCount
   * @return voteCount
  **/
  @ApiModelProperty(value = "")
  public Integer getVoteCount() {
    return voteCount;
  }

  public void setVoteCount(Integer voteCount) {
    this.voteCount = voteCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieDetailsObject movieDetailsObject = (MovieDetailsObject) o;
    return Objects.equals(this.adult, movieDetailsObject.adult) &&
        Objects.equals(this.backdropPath, movieDetailsObject.backdropPath) &&
        Objects.equals(this.budget, movieDetailsObject.budget) &&
        Objects.equals(this.genres, movieDetailsObject.genres) &&
        Objects.equals(this.homepage, movieDetailsObject.homepage) &&
        Objects.equals(this.id, movieDetailsObject.id) &&
        Objects.equals(this.imdbId, movieDetailsObject.imdbId) &&
        Objects.equals(this.originalLanguage, movieDetailsObject.originalLanguage) &&
        Objects.equals(this.originalTitle, movieDetailsObject.originalTitle) &&
        Objects.equals(this.overview, movieDetailsObject.overview) &&
        Objects.equals(this.popularity, movieDetailsObject.popularity) &&
        Objects.equals(this.posterPath, movieDetailsObject.posterPath) &&
        Objects.equals(this.productionCompanies, movieDetailsObject.productionCompanies) &&
        Objects.equals(this.productionCountries, movieDetailsObject.productionCountries) &&
        Objects.equals(this.releaseDate, movieDetailsObject.releaseDate) &&
        Objects.equals(this.revenue, movieDetailsObject.revenue) &&
        Objects.equals(this.runtime, movieDetailsObject.runtime) &&
        Objects.equals(this.spokenLanguages, movieDetailsObject.spokenLanguages) &&
        Objects.equals(this.status, movieDetailsObject.status) &&
        Objects.equals(this.tagline, movieDetailsObject.tagline) &&
        Objects.equals(this.title, movieDetailsObject.title) &&
        Objects.equals(this.video, movieDetailsObject.video) &&
        Objects.equals(this.voteAverage, movieDetailsObject.voteAverage) &&
        Objects.equals(this.voteCount, movieDetailsObject.voteCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adult, backdropPath, budget, genres, homepage, id, imdbId, originalLanguage, originalTitle, overview, popularity, posterPath, productionCompanies, productionCountries, releaseDate, revenue, runtime, spokenLanguages, status, tagline, title, video, voteAverage, voteCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovieDetailsObject {\n");
    
    sb.append("    adult: ").append(toIndentedString(adult)).append("\n");
    sb.append("    backdropPath: ").append(toIndentedString(backdropPath)).append("\n");
    sb.append("    budget: ").append(toIndentedString(budget)).append("\n");
    sb.append("    genres: ").append(toIndentedString(genres)).append("\n");
    sb.append("    homepage: ").append(toIndentedString(homepage)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imdbId: ").append(toIndentedString(imdbId)).append("\n");
    sb.append("    originalLanguage: ").append(toIndentedString(originalLanguage)).append("\n");
    sb.append("    originalTitle: ").append(toIndentedString(originalTitle)).append("\n");
    sb.append("    overview: ").append(toIndentedString(overview)).append("\n");
    sb.append("    popularity: ").append(toIndentedString(popularity)).append("\n");
    sb.append("    posterPath: ").append(toIndentedString(posterPath)).append("\n");
    sb.append("    productionCompanies: ").append(toIndentedString(productionCompanies)).append("\n");
    sb.append("    productionCountries: ").append(toIndentedString(productionCountries)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
    sb.append("    spokenLanguages: ").append(toIndentedString(spokenLanguages)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tagline: ").append(toIndentedString(tagline)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    voteAverage: ").append(toIndentedString(voteAverage)).append("\n");
    sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

